defaults:
  - main
  - _self_

default_fillers:
  partition: "booster"
  job_name: "juwels"
  time: "24:00:00"
  cpus: "48"
  mem: "515000mb"
  gres: "gpu:4"
  additional_sbatch_configs: '#SBATCH --account=aimatchem'

NO_gpus: 4
max_tasks: null